workflows:
  ios-workflow:
    name: Muzik iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          # Eğer ana dizinde Podfile varsa direkt çalıştırırız
          pod install
      - name: Build iOS (Unsigned)
        script: |
          # Proje ismi 'muzik' olarak güncellendi
          xcodebuild -workspace muzik.xcworkspace \
            -scheme muzik \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGN_ENTITLEMENTS="" \
            GCC_GENERATE_DEBUGGING_SYMBOLS=NO \
            build
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
